import { Helmet } from "react-helmet-async";

const sections = [
  { title: "1. Acceptance of terms", body: "By creating an account or using SkillProof AI you agree to these Terms of Service and our Privacy Policy." },
  { title: "2. Account responsibilities", body: "You're responsible for safeguarding your credentials and for any activity under your account. Notify us immediately of any unauthorized use." },
  { title: "3. Acceptable use", body: "Do not upload content you don't own, attempt to reverse-engineer the platform, scrape data, or use the service to harass, defraud, or misrepresent identity." },
  { title: "4. Content ownership", body: "You retain ownership of resumes, certificates, and other content you upload. You grant us a limited license to process and display this content solely to provide the service." },
  { title: "5. AI-generated output", body: "ATS scores, suggestions, and analyses are generated by AI and provided as guidance only. We do not guarantee hiring outcomes." },
  { title: "6. Subscriptions and billing", body: "Paid plans renew automatically until canceled. Refunds are handled case-by-case under our refund policy." },
  { title: "7. Termination", body: "We may suspend or terminate accounts that violate these terms. You may close your account at any time from Settings." },
  { title: "8. Disclaimer", body: "The service is provided 'as is' without warranties of any kind. To the maximum extent permitted by law, our liability is limited to the amount you paid us in the prior 12 months." },
  { title: "9. Governing law", body: "These terms are governed by the laws of Delaware, USA. Disputes will be resolved by binding arbitration unless prohibited by your local law." },
  { title: "10. Contact", body: "Questions about these terms? Email legal@skillproof.ai." },
];

export default function Terms() {
  return (
    <>
      <Helmet>
        <title>Terms of Service — SkillProof AI</title>
        <meta name="description" content="The terms governing use of the SkillProof AI platform — your responsibilities, content ownership, and legal disclaimers." />
        <link rel="canonical" href="/terms" />
      </Helmet>

      <article className="container-tight max-w-3xl py-24">
        <p className="font-mono text-xs uppercase tracking-wider text-muted-foreground">Legal</p>
        <h1 className="mt-2 font-display text-4xl font-semibold tracking-tight md:text-5xl">Terms of Service</h1>
        <p className="mt-3 text-sm text-muted-foreground">Last updated: May 21, 2026</p>

        <div className="mt-10 space-y-8">
          {sections.map((s) => (
            <section key={s.title}>
              <h2 className="font-display text-xl font-semibold">{s.title}</h2>
              <p className="mt-2 text-muted-foreground">{s.body}</p>
            </section>
          ))}
        </div>
      </article>
    </>
  );
}
